#!/bin/bash

cd .scripts/kafka-connector/debezium/config/
pwd

URL="127.0.0.1:8083/connectors/"

curl -i -X POST -H "Accept:application/json" -H "Content-Type:application/json" ${URL} --data "@debezium.json"

echo