#!/bin/bash

# https://nightlies.apache.org/flink/flink-docs-release-1.16/docs/dev/configuration/overview/

VERSION="1.16.0"

mvn archetype:generate                \
  -DarchetypeGroupId=org.apache.flink   \
  -DarchetypeArtifactId=flink-quickstart-java \
  -DarchetypeVersion=${VERSION}