-- connect to XEPDB1 - Service Names

-- Needed to insert data into the table
GRANT UNLIMITED TABLESPACE TO ABCD;

CREATE TABLE ABCD.STUDENT (
	ID INTEGER GENERATED ALWAYS AS IDENTITY NOT NULL, 
	NAME VARCHAR2(255) NOT NULL, 
    TIMESTAMP DATE NOT NULL,
	CONSTRAINT "STUDENT_PK" PRIMARY KEY ("ID")
);

INSERT INTO ABCD.STUDENT (name, TIMESTAMP) VALUES ('Song Li', CURRENT_DATE);